//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBConnector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add at least one value to method AddColumnsSelect or specify optional parameter allColumns as true.
        /// </summary>
        internal static string exceptionAddColumnsSelect {
            get {
                return ResourceManager.GetString("exceptionAddColumnsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add at least one query to method AddQuerySQLTransaction.
        /// </summary>
        internal static string exceptionAddQuerySQLTransaction {
            get {
                return ResourceManager.GetString("exceptionAddQuerySQLTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add at least one value to method AddValuesForQuery.
        /// </summary>
        internal static string exceptionAddValueForQuery {
            get {
                return ResourceManager.GetString("exceptionAddValueForQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add at least one value to method AddValuesWhere.
        /// </summary>
        internal static string exceptionAddValueWhere {
            get {
                return ResourceManager.GetString("exceptionAddValueWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters can&apos;t be Null or Empty.
        /// </summary>
        internal static string exceptionParametersNullOrEmpty {
            get {
                return ResourceManager.GetString("exceptionParametersNullOrEmpty", resourceCulture);
            }
        }
    }
}
